### ISSUE TITLE
해상도 조정

### ISSUE THREAD

**Issue by gomse** [shanash/UnityPuzzle#2]
게임 해상도가 어떻게 되나요?
디바이스별로 해상도가 자동으로 조정되도록 맞춰줘야 합니다.

**Comment by gomse** [comment]
블럭의 사이즈는 가로x세로=40x40
맵의 크기는 가로에 블럭 8개 = 40x8 = 320, 세로는 12개 = 40x12 = 480 (320x480)

**Comment by shanash** [comment]
현재 498 x 280으로 게임이 진행되는 맵공간은 밑의 다섯줄뿐입니다.
![2015-02-15 10 29 44](https://cloud.githubusercontent.com/assets/8412989/6201729/b38f5dd0-b4fd-11e4-8c26-295a935cc3a7.png)

**Comment by gomse** [comment]
그럼 커튼이라는 오브젝트는 단지 가리기 위한 거였나!?
498x280이라는 해상도는 대체 어디서 나온건가요 (...)

**Comment by shanash** [comment]
블럭 크기를 40으로 잡으니 세로 크기를 280 정도로 잡아야 할거 같았고 498은 그냥 16:9 해상도로 하니깐 저렇게 나오더라고요[...]
